version: "2"

services:
  cats:
    build: cats
    ports:
     - "5000:5000"

  mongodb:
    image: mongo
    #build: mongo
    ports:
     - "37017:27017"

  mongo-seed:
    build: mongo-seed
    links:
     - mongodb

  redis:
    image: redis
